/*
  services/offline.ts — registers the service worker (hosted site only).

  Defines : registerServiceWorker().
  Used by : platform.ts (mode "site").
  Uses    : sw.js, generated by the build next to index.html.
*/

export function registerServiceWorker(url = "sw.js"): void {
  if (!("serviceWorker" in navigator)) return;
  navigator.serviceWorker.register(url)
    .catch((err: Error) => console.warn(`Service worker not registered: ${err.message}`));
}
