/*
  core/strings.ts — the platform's own UI strings (English, French).

  Defines : PLATFORM_STRINGS.
  Used by : platform.ts (creates the i18n with them; apps add theirs on top).
  Uses    : core/i18n.ts (type only).
*/
import type { StringTable } from "./i18n.ts";

export const PLATFORM_STRINGS: StringTable = {
  en: {
    download: "Download", downloadTitle: "Offline copy: a single HTML file",
    install: "Install", installTitle: "Install the app (updates itself)",
    checkUpdate: "Check for updates", privacy: "Privacy",
    offlineCopy: "Offline copy — version {version} ({date})",
    upToDate: "Up to date", updateAvailable: "A new version is available",
    updateDownload: "download it", updateUnknown: "Could not check for updates",
    newTab: "(opens in a new tab)",
    consentTitle: "Allow a connection?",
    consentIntro: "This app works locally. This action needs to contact an external server.",
    consentOrigin: "Server", consentPurpose: "Purpose", consentSent: "Visible to that server",
    consentSentText: "your IP address and the requested address (URL)",
    deny: "Deny", session: "Allow for this session", always: "Always allow",
    once: "Send once", consentSentValue: "This exact value:", consentReferrer: "Address of this page",
    referrerNone: "Not sent", referrerOrigin: "This site's address only (not the page or its content)",
    stateRequest: "Asked every time",
    shareTitle: "Share a link", shareCopy: "Copy link", cancel: "Cancel",
    shareWarning: "The link contains the data listed below. Anyone who gets the link can read it, and it may stay in browser history, chats or e-mails. This app sends it to no server.",
    shareManual: "Copy this link manually:",
    assetSiteOnly: "Available on the hosted site only",
    supportLink: "Buy me a coffee", devBuild: "Dev build",
    accessibility: "Accessibility", shortcutsToggle: "Single-key keyboard shortcuts",
    shortcutsHint: "Turn them off if you use voice control or a switch device: a spoken word could trigger them.",
    shortcutsNone: "This app has no single-key shortcuts.", themeLegend: "Theme",
    theme_system: "Like the system", theme_light: "Light", theme_dark: "Dark",
    privacyIntro: "External servers this app may contact, and your decisions. Data you enter stays in this browser.",
    stateAlways: "Always allowed", stateSession: "Allowed (session)", stateDenied: "Denied (session)",
    stateAsk: "Ask each time", forget: "Forget", clearData: "Clear all local data", close: "Close",
    clearConfirm: "Delete all data this app stored in this browser?",
    purposeUpdate: "Check whether a newer version is available",
    installHelpTitle: "Install the app",
    installHelpIntro: "Once installed, the app opens offline and updates itself.",
    installIos: "iPhone / iPad (Safari): Share button → “Add to Home Screen”.",
    installMac: "Mac (Safari 17 or later): File menu → “Add to Dock”.",
    installChromium: "Chrome / Edge (computer): “Install” icon in the address bar, or in the browser menu.",
    installAndroid: "Android (Chrome): menu ⋮ → “Install app” or “Add to Home screen”.",
    installOther: "Other browsers (e.g. Firefox on a computer): use “Download” instead.",
  },
  fr: {
    download: "Télécharger", downloadTitle: "Copie hors ligne : un seul fichier HTML",
    install: "Installer", installTitle: "Installer l'application (se met à jour seule)",
    checkUpdate: "Vérifier les mises à jour", privacy: "Confidentialité",
    offlineCopy: "Copie hors ligne — version {version} ({date})",
    upToDate: "À jour", updateAvailable: "Une nouvelle version est disponible",
    updateDownload: "la télécharger", updateUnknown: "Impossible de vérifier les mises à jour",
    newTab: "(s'ouvre dans un nouvel onglet)",
    consentTitle: "Autoriser une connexion ?",
    consentIntro: "Cette application fonctionne en local. Cette action doit contacter un serveur externe.",
    consentOrigin: "Serveur", consentPurpose: "But", consentSent: "Visible par ce serveur",
    consentSentText: "votre adresse IP et l'adresse demandée (URL)",
    deny: "Refuser", session: "Autoriser pour cette session", always: "Toujours autoriser",
    once: "Envoyer une fois", consentSentValue: "Cette valeur exacte :", consentReferrer: "Adresse de cette page",
    referrerNone: "Non transmise", referrerOrigin: "Uniquement l'adresse de ce site (ni la page, ni son contenu)",
    stateRequest: "Demandé à chaque fois",
    shareTitle: "Partager un lien", shareCopy: "Copier le lien", cancel: "Annuler",
    shareWarning: "Le lien contient les données ci-dessous. Toute personne qui le reçoit peut les lire, et il peut rester dans l'historique, des messageries ou des e-mails. Cette application ne l'envoie à aucun serveur.",
    shareManual: "Copiez ce lien manuellement :",
    assetSiteOnly: "Disponible uniquement sur le site en ligne",
    supportLink: "Offrez-moi un café", devBuild: "Version de développement",
    accessibility: "Accessibilité", shortcutsToggle: "Raccourcis clavier à une touche",
    shortcutsHint: "Désactivez-les si vous utilisez le contrôle vocal ou un contacteur : un mot prononcé pourrait les déclencher.",
    shortcutsNone: "Cette application n'a pas de raccourci à une touche.", themeLegend: "Thème",
    theme_system: "Comme le système", theme_light: "Clair", theme_dark: "Sombre",
    privacyIntro: "Serveurs externes que cette application peut contacter, et vos choix. Vos saisies restent dans ce navigateur.",
    stateAlways: "Toujours autorisé", stateSession: "Autorisé (session)", stateDenied: "Refusé (session)",
    stateAsk: "Demander à chaque fois", forget: "Oublier", clearData: "Effacer toutes les données locales", close: "Fermer",
    clearConfirm: "Supprimer toutes les données de cette application dans ce navigateur ?",
    purposeUpdate: "Vérifier si une version plus récente est disponible",
    installHelpTitle: "Installer l'application",
    installHelpIntro: "Une fois installée, l'application s'ouvre hors ligne et se met à jour seule.",
    installIos: "iPhone / iPad (Safari) : bouton Partager → « Sur l'écran d'accueil ».",
    installMac: "Mac (Safari 17 ou plus récent) : menu Fichier → « Ajouter au Dock ».",
    installChromium: "Chrome / Edge (ordinateur) : icône « Installer » dans la barre d'adresse, ou dans le menu du navigateur.",
    installAndroid: "Android (Chrome) : menu ⋮ → « Installer l'application » ou « Ajouter à l'écran d'accueil ».",
    installOther: "Autres navigateurs (p. ex. Firefox sur ordinateur) : utilisez plutôt « Télécharger ».",
  },
};
