"""assemble.py — turns the page shell + bundle into the two outputs and their companions.

Defines : config_js(), render_page(), manifest_json(), headers_file(), service_worker().
Used by : builder.py.
Uses    : csp.py; the app's src/index.html (with BUILD:HEAD / BUILD:BODY
          markers) and src/icons/icon.svg; the platform's ui/base.css and sw.js.
"""

import base64
import json
import re

from swp_tools.bundle import AppBundle
from swp_tools.config import Project
from swp_tools.csp import build_csp

HEAD_MARKER = "<!-- BUILD:HEAD -->"
BODY_MARKER = "<!-- BUILD:BODY -->"
SITE_CONFIG_KEYS = ("id", "title", "lang", "siteUrl", "downloadName", "netOrigins", "options")
VERSION_FILENAME = "version.json"


def config_js(site: dict, mode: str, version: str, date: str, assets: list[str] | None = None) -> str:
    config = {key: site[key] for key in SITE_CONFIG_KEYS}
    config.update(mode=mode, version=version, date=date, assets=assets or [],
                  workers=sorted(site.get("workers", {})),
                  themeSwitch=bool(site.get("themeSwitch", False)))
    return ("// config.js — GENERATED by the platform build (swp) from src/site.json. Do not edit.\n"
            f"window.__SWP_SITE__ = {json.dumps(config, ensure_ascii=False, indent=2)};\n")


_SCRIPT_HAZARD = re.compile(r"<(?:/?script|!--)", re.IGNORECASE)
_STYLE_HAZARD = re.compile(r"</style", re.IGNORECASE)


def inline_js(code: str) -> str:
    """Make JavaScript safe to place inside <script>…</script>.

    HOW: "</script" would end the element early; "<!--" followed later by
    "<script" switches the HTML parser into a state where "</script>" no
    longer ends it, swallowing the rest of the page (HTML spec, script data
    double-escaped state — hit by the Svelte runtime, which contains "<!--").
    Each sequence is rewritten with an escape that means the same character
    inside JavaScript strings, template literals and regular expressions
    (including /u ones): "<\\/script", "<\\x73cript", "<\\x21--".
    WHY not escape everywhere blindly: these escapes are only valid inside
    literals; the bundle is not minified, so such sequences only occur there.
    """
    code = re.sub(r"</(s)(?=cript)", lambda m: "<\\/" + m.group(1), code, flags=re.IGNORECASE)
    code = re.sub(r"<(s)(?=cript)", lambda m: "<\\x73" if m.group(1) == "s" else "<\\x53", code, flags=re.IGNORECASE)
    code = code.replace("<!--", "<\\x21--")
    # Invariant: nothing that could end or re-open the script element remains;
    # otherwise the single file would be silently truncated in the browser.
    if _SCRIPT_HAZARD.search(code):
        raise SystemExit("Cannot inline the app safely: a '<script' / '<!--' sequence remains")
    return code


def inline_css(code: str) -> str:
    """Make CSS safe to place inside <style>…</style> ("</style" would end it)."""
    code = re.sub(r"</(s)(?=tyle)", lambda m: "<\\/" + m.group(1), code, flags=re.IGNORECASE)
    if _STYLE_HAZARD.search(code):
        raise SystemExit("Cannot inline the styles safely: a '</style' sequence remains")
    return code


def platform_css(project: Project) -> str:
    return (project.platform_dir / "src" / "ui" / "base.css").read_text(encoding="utf-8")


def render_page(project: Project, mode: str, bundle: AppBundle, version: str, date: str,
                assets: list[str]) -> str:
    site = project.site
    shell = (project.src / "index.html").read_text(encoding="utf-8")
    # Invariant: each marker exactly once — otherwise CSS/JS would be injected
    # twice or not at all and the page silently broken.
    for marker in (HEAD_MARKER, BODY_MARKER):
        if shell.count(marker) != 1:
            raise SystemExit(f"src/index.html must contain {marker} exactly once")
    head = [
        f'<meta http-equiv="Content-Security-Policy" content="{build_csp(site, mode)}">',
        '<meta name="referrer" content="no-referrer">',
        '<meta http-equiv="x-dns-prefetch-control" content="off">',
        f'<meta name="theme-color" content="{site["themeColor"]}">',
        f"<title>{site['title']}</title>",
    ]
    if mode == "site":
        head += ['<link rel="icon" href="icons/icon.svg" type="image/svg+xml">',
                 '<link rel="manifest" href="manifest.webmanifest">',
                 '<link rel="apple-touch-icon" href="icons/apple-touch-icon.png">',
                 '<link rel="stylesheet" href="base.css">']
        if bundle.css:
            head.append('<link rel="stylesheet" href="app.css">')
        body = ['<script src="config.js"></script>', '<script src="app.js"></script>']
    else:
        icon = base64.b64encode((project.src / "icons" / "icon.svg").read_bytes()).decode()
        head.append(f'<link rel="icon" href="data:image/svg+xml;base64,{icon}">')
        css = inline_css(platform_css(project) + "\n" + bundle.css)
        head.append(f"<style>\n{css}</style>")
        # Workers: inert text (type="text/plain" is never executed); the
        # platform turns it into a blob: Worker (CSP worker-src blob:).
        body = [f'<script type="text/plain" id="swp-worker-{name}">\n{inline_js(code)}</script>'
                for name, code in sorted(bundle.workers.items())]
        body += [f"<script>\n{inline_js(config_js(site, mode, version, date, assets))}</script>",
                 f"<script>\n{inline_js(bundle.js)}</script>"]
    return shell.replace(HEAD_MARKER, "\n".join(head)).replace(BODY_MARKER, "\n".join(body))


def manifest_json(site: dict) -> str:
    return json.dumps({
        "name": site["title"], "short_name": site["shortName"], "lang": site["lang"],
        "start_url": "./", "scope": "./", "display": "standalone",
        "background_color": site["themeColor"], "theme_color": site["themeColor"],
        "icons": [
            {"src": "icons/icon-192.png", "sizes": "192x192", "type": "image/png"},
            {"src": "icons/icon-512.png", "sizes": "512x512", "type": "image/png"},
            {"src": "icons/icon.svg", "sizes": "any", "type": "image/svg+xml"},
        ],
    }, ensure_ascii=False, indent=2) + "\n"


def headers_file(site: dict) -> str:
    # The full CSP is the <meta> of each page (the single file needs a looser
    # one than the site); the header only adds what a <meta> cannot carry.
    return f"""# _headers — GENERATED by the platform build (swp). Cloudflare Pages response headers.

/*
  Content-Security-Policy: frame-ancestors 'none'
  X-Content-Type-Options: nosniff
  Referrer-Policy: no-referrer
  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=()

/{VERSION_FILENAME}
  Access-Control-Allow-Origin: *
  Cache-Control: no-cache

/sw.js
  Cache-Control: no-cache

/{site["downloadName"]}
  Content-Disposition: attachment; filename="{site["downloadName"]}"
"""


def service_worker(project: Project, version: str, precache: list[str]) -> str:
    source = (project.platform_dir / "src" / "sw.js").read_text(encoding="utf-8")
    return (source.replace("__CACHE_NAME__", f"{project.site['id']}-{version}")
                  .replace("__PRECACHE__", json.dumps(precache)))
